version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  groups:
    python-dependencies:
      # A pattern can be...
      patterns:
      - '*'
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
