version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: weekly
  groups:
    python-dependencies:
      # A pattern can be...
      patterns:
      - '*'    
- package-ecosystem: "github-actions"
  directory: ".github/"
  schedule:
    interval: weekly
