[tool.poetry]
name = "rds-metadata-exporter"
version = "0.1.0"
description = ""
authors = ["Gabi Davar <grizzly.nyo@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
prometheus-client = "^0.20.0"
botocore = "^1.34.97"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
mypy = "^1.10.0"
ruff = "^0.4.2"
#pytest = "~7.4.4"
#coverage = { version = "~7.3.2", extras = ["toml"] }
#pytest-asyncio = "~0.23.6"
#pytest-kubernetes = "~0.3.0"
#types-requests = "^2.31.0.2"
types-pyyaml = "^6.0.12.20240311"
memray = "^1.12.0"

[build-system]
requires = ["poetry-core>=1.8.2,<2"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py312"
